import type { InstitutionalLookupResponse } from "@smart-campus/contracts";

/**
 * Safe client fallback records for unit tests and fully offline mock mode.
 * Private directory fields such as raw phone numbers and email addresses stay
 * in the server-only mock directory and are never bundled into browser code.
 */
export const MOCK_PUBLIC_DIRECTORY: InstitutionalLookupResponse[] = [
  {
    id: "33333333-3333-3333-3333-333333330001",
    institutionalId: "STU2026001",
    fullName: "Aarav Sharma",
    maskedPhone: "+91 ******0001",
    role: "student",
    departmentCode: "CSE",
    departmentName: "Computer Science & Engineering",
    programCode: "BTECH_CSE",
    programName: "Bachelor of Technology in Computer Science & Engineering",
    academicYear: 3,
    semester: 6,
    section: "A",
    designation: null,
    tags: ["CAS_COORDINATOR"],
    isActive: true,
  },
  {
    id: "33333333-3333-3333-3333-333333330002",
    institutionalId: "STU2026002",
    fullName: "Diya Patel",
    maskedPhone: "+91 ******0002",
    role: "student",
    departmentCode: "CSE",
    departmentName: "Computer Science & Engineering",
    programCode: "BTECH_CSE",
    programName: "Bachelor of Technology in Computer Science & Engineering",
    academicYear: 3,
    semester: 6,
    section: "A",
    designation: null,
    tags: [],
    isActive: true,
  },
  {
    id: "44444444-4444-4444-4444-444444440001",
    institutionalId: "FAC1001",
    fullName: "Dr. Sundar Pichai",
    maskedPhone: "+91 ******0001",
    role: "faculty",
    departmentCode: "CSE",
    departmentName: "Computer Science & Engineering",
    programCode: null,
    programName: null,
    academicYear: null,
    semester: null,
    section: null,
    designation: "Professor",
    tags: ["COURSE_COORDINATOR"],
    isActive: true,
  },
  {
    id: "44444444-4444-4444-4444-444444440011",
    institutionalId: "FAC1011",
    fullName: "Dr. Aris Thorne",
    maskedPhone: "+91 ******0001",
    role: "faculty",
    departmentCode: "CSE",
    departmentName: "Computer Science & Engineering",
    programCode: null,
    programName: null,
    academicYear: null,
    semester: null,
    section: null,
    designation: "Professor & Head of Department (CSE)",
    tags: ["HOD", "DEPARTMENT_COORDINATOR"],
    isActive: true,
  },
];
